name: Build pc-ble-driver-py
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
env:
  NRF_BLE_DRIVER_VERSION: 4.1.100
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-13, windows-2019 ]
        python-version: [ '3.10', '3.11' ]
        include:
          - python-version: '3.10'
            toxpy: py310
          - python-version: '3.11'
            toxpy: py311
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: pc-ble-driver-py

    - name: Checkout pc-ble-driver
      uses: actions/checkout@v4
      with:
        repository: NordicSemiconductor/pc-ble-driver
        ref: c0ffd419053e2405fffdb02ce7f1f9acceff4a66
        path: pc-ble-driver

    - name: Install linux dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y build-essential libspdlog-dev libasio-dev libudev-dev

    - name: Install macos dependencies
      if: runner.os == 'macOS'
      run: brew install asio spdlog

    - name: Install windows dependencies
      if: runner.os == 'Windows'
      env:
        VCPKG_ROOT: C:\vcpkg
      run: |
        echo "VCPKG_ROOT=${{ env.VCPKG_ROOT }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        vcpkg install --triplet x64-windows asio spdlog

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      working-directory: pc-ble-driver-py
      run: python -m pip install -r requirements-dev.txt

    - name: Compile pc-ble-driver
      if: runner.os != 'Windows'
      working-directory: pc-ble-driver
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DDISABLE_TESTS=1 -DNRF_BLE_DRIVER_VERSION=${{ env.NRF_BLE_DRIVER_VERSION }} -G "Unix Makefiles" ..
        make nrf_ble_driver_sd_api_v5_static
        sudo make install

    - name: Compile pc-ble-driver windows
      if: runner.os == 'Windows'
      working-directory: pc-ble-driver
      run: |
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DDISABLE_TESTS=1 "-DNRF_BLE_DRIVER_VERSION=${{ env.NRF_BLE_DRIVER_VERSION }}" -G "Visual Studio 16 2019" -A x64 ..
        cmake --build . --config Release
        cmake --install . --config Release

    - name: Build pc-ble-driver-py wheels
      if: runner.os != 'Windows'
      working-directory: pc-ble-driver-py
      run: |
        python setup.py bdist_wheel --build-type Release

    - name: Build pc-ble-driver-py wheels windows
      if: runner.os == 'Windows'
      working-directory: pc-ble-driver-py
      run: |
        python setup.py bdist_wheel --build-type Release -G "Visual Studio 16 2019" --skip-generator-test

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pc_ble_driver_py-${{ matrix.os }}-${{ matrix.toxpy}}
        path: "pc-ble-driver-py/dist/*.whl"
        if-no-files-found: error
  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: upload release assets
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: flatten folder structure
        working-directory: dist
        run: |
          find . -name '*.whl' -exec mv {} . \;
          find . -type d -empty -delete

          # list files
          ls -R

      - name: upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
