name: Build pc-ble-driver-py
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
env:
  NRF_BLE_DRIVER_VERSION: 4.1.100
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            arch: x86_64
          - os: ubuntu-20.04
            arch: aarch64
          - os: macos-latest
            arch: x86_64
          - os: macos-latest
            arch: arm64
          - os: windows-2019
            arch: AMD64
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout pc-ble-driver
      uses: actions/checkout@v4
      with:
        repository: NordicSemiconductor/pc-ble-driver
        ref: c0ffd419053e2405fffdb02ce7f1f9acceff4a66
        path: pc-ble-driver

    - name: Set up QEMU
      if: matrix.arch == 'aarch64' && runner.os == 'Linux'
      uses: docker/setup-qemu-action@v3

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.19.2
      env:
        CIBW_BUILD_VERBOSITY: 1
        CIBW_ARCHS: ${{ matrix.arch }}
      with:
        output-dir: dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pc_ble_driver_py-${{ matrix.os }}-${{ matrix.arch }}
        path: "dist/*.whl"
        if-no-files-found: error

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    name: upload release assets
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: flatten folder structure
        working-directory: dist
        run: |
          find . -name '*.whl' -exec mv {} . \;
          find . -type d -empty -delete

          # list files
          ls -R

      - name: upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
